### ISSUE TITLE
Prebuilt unbound-exporter binary

### ISSUE THREAD

**Issue by jmanoelslva** [ar51an/unbound-exporter#1]
Hello,

Do you have the unbound-exporter binary for amd64?

**Comment by ar51an** [comment]
Hello,
I uploaded the linux-amd64 unbound-exporter binary under below link:

https://github.com/ar51an/unbound-exporter/blob/main/bin/amd64/

Let me know if you face any issues.

**Comment by jmanoelslva** [comment]
Firstly,

Thanks a lot. 

I've changed some parameters to fit to my environment and it's working perfectly.
